Repository FragLand/terracord, pull requests merged in 2020-01, with the labels that each got.

#15 Add logging and dispose Discord bot client on shutdown
  Terracord/Terracord.cs
  terracord.xml
Labels: new feature

#17 Add debug mode
  Terracord/Terracord.cs
  terracord.xml
Labels: enhancement

#19 Various fixes, improvements, and documentation
  .github/ISSUE_TEMPLATE/bug-report.md
  Terracord/Terracord.cs
Labels: bug, documentation, enhancement, hygiene, new feature

#21 More various improvements
  .github/README.md
  Terracord/Terracord.cs
  terracord.xml
Labels: documentation, enhancement, hygiene, new feature

#29 Refactor all the things
  .codeclimate.yml
  Terracord/Config.cs
  Terracord/Discord.cs
  Terracord/Terracord.cs
  Terracord/Terracord.csproj
  Terracord/Util.cs
Labels: hygiene

#31 Add log severity and corresponding console colors
  Terracord/Config.cs
  Terracord/Discord.cs
  Terracord/Terracord.cs
  Terracord/Util.cs
Labels: enhancement

#34 Add playerlist, serverinfo, and uptime commands
  Terracord/Config.cs
  Terracord/Discord.cs
  Terracord/Terracord.cs
  Terracord/Terracord.csproj
  Terracord/Util.cs
Labels: new feature

#35 Convert received Discord mentions and change uptime command to embed
  Terracord/Discord.cs
  Terracord/Terracord.cs
Labels: new feature

#36 Periodic topic update
  Terracord/Config.cs
  Terracord/Discord.cs
  terracord.xml
Labels: new feature

#37 Add typing status prior to command response
  Terracord/Discord.cs
Labels: new feature

#40 Improved command specifier relay denial
  Terracord/Terracord.cs
Labels: bug, enhancement

#42 Fixes, localization, and some unit testing
  Terracord.sln
  Terracord/Config.cs
  Terracord/Discord.cs
  Terracord/Properties/Strings.Designer.cs
  Terracord/Properties/Strings.ar.resx
  Terracord/Properties/Strings.de.resx
  Terracord/Properties/Strings.en.resx
  Terracord/Properties/Strings.es.resx
  Terracord/Properties/Strings.fr.resx
  Terracord/Properties/Strings.it.resx
  Terracord/Properties/Strings.ja.resx
  Terracord/Properties/Strings.ko.resx
  Terracord/Properties/Strings.nl.resx
  Terracord/Properties/Strings.pl.resx
  Terracord/Properties/Strings.pt.resx
  Terracord/Properties/Strings.resx
  Terracord/Properties/Strings.ru.resx
  Terracord/Properties/Strings.zh.resx
  Terracord/Terracord.cs
  Terracord/Terracord.csproj
  Terracord/Util.cs
  TerracordTest/TerracordTest.cs
  TerracordTest/TerracordTest.csproj
  terracord.xml
Labels: enhancement, hygiene, new feature

#45 Add mention and custom emote conversion
  Terracord/Discord.cs
  Terracord/Terracord.cs
  Terracord/Util.cs
Labels: new feature

#48 Player event and mention fixes, README.md localization instructions
  .github/README.md
  Terracord/Properties/Strings.Designer.cs
  Terracord/Properties/Strings.ar.resx
  Terracord/Properties/Strings.de.resx
  Terracord/Properties/Strings.en.resx
  Terracord/Properties/Strings.es.resx
  Terracord/Properties/Strings.fr.resx
  Terracord/Properties/Strings.it.resx
  Terracord/Properties/Strings.ja.resx
  Terracord/Properties/Strings.ko.resx
  Terracord/Properties/Strings.nl.resx
  Terracord/Properties/Strings.pl.resx
  Terracord/Properties/Strings.pt.resx
  Terracord/Properties/Strings.resx
  Terracord/Terracord.cs
  Terracord/Util.cs
Labels: bug, documentation, enhancement

#55 Do some refactoring and add Discord attachment support
  Terracord/Discord.cs
  Terracord/Util.cs
Labels: enhancement, hygiene, new feature

#57 Add reload support
  Terracord/Terracord.cs
Labels: new feature

#58 Change config file and log file path
  .github/README.md
  Terracord/Config.cs
  Terracord/Util.cs
Labels: documentation, enhancement, hygiene

#59 Path fixes
  Terracord/Config.cs
  Terracord/Util.cs
Labels: bug, enhancement

#60 Add remote TShock commands
  Terracord/Command.cs
  Terracord/Config.cs
  Terracord/Discord.cs
Labels: new feature
