Repository FragLand/terracord, pull requests merged in 2020-11, with the labels that each got.

#109 Allow bot command prefixes longer than 1 character.
  Terracord/Command.cs
  Terracord/Config.cs
  Terracord/Discord.cs
  Terracord/Properties/Strings.Designer.cs
  Terracord/Properties/Strings.ar.resx
  Terracord/Properties/Strings.de.resx
  Terracord/Properties/Strings.en.resx
  Terracord/Properties/Strings.es.resx
  Terracord/Properties/Strings.fr.resx
  Terracord/Properties/Strings.it.resx
  Terracord/Properties/Strings.ja.resx
  Terracord/Properties/Strings.ko.resx
  Terracord/Properties/Strings.nl.resx
  Terracord/Properties/Strings.pl.resx
  Terracord/Properties/Strings.pt.resx
  Terracord/Properties/Strings.resx
  Terracord/Properties/Strings.ru.resx
  Terracord/Properties/Strings.zh.resx
  TerracordTest/TerracordTest.cs
Labels: enhancement

#110 Fix bug relating to command prefixes and leading whitespace
  Terracord/Command.cs
Labels: bug

#112 Add basic Discord bot permission info
  .github/README.md
Labels: documentation
